export enum EAdminAction {
  BLOCK_USER = 'BLOCK_USER',
  UNBLOCK_USER = 'UNBLOCK_USER',
  DELETE_USER = 'DELETE_USER',
  CREATE_ADMIN = 'CREATE_ADMIN',
  EDIT_ADMIN = 'EDIT_ADMIN',
  DELETE_ADMIN = 'DELETE_ADMIN',
}

export const CODE_EXPIRY_MINUTES = 5;
export const MAX_RESEND_COUNT = 3;
export const RESEND_INTERVAL_SECONDS = 30;
export const MAX_VERIFICATION_ATTEMPTS = 5;
export const RESEND_WINDOW_SECONDS = 60;
