export const MAIL_QUEUE = 'MAIL_QUEUE';
export const FILE_UPLOAD_QUEUE = 'FILE_UPLOAD_QUEUE';
export const SYSTEM_MESSAGE_QUEUE = 'SYSTEM_MESSAGE_QUEUE';
export const QUESTION_BANK_QUEUE = 'QUESTION_BANK_QUEUE';

export const FILE_UPLOAD_JOB = {
  UPLOAD_ATTACHMENT: 'UPLOAD_ATTACHMENT',
  UPLOAD_CONVERSATION_AVATAR: 'UPLOAD_CONVERSATION_AVATAR',
  UPLOAD_USER_AVATAR: 'UPLOAD_USER_AVATAR',
  UPLOAD_USER_BACKGROUND: 'UPLOAD_USER_BACKGROUND',
  UPLOAD_ASSIGNMENT_ATTACHMENT: 'UPLOAD_ASSIGNMENT_ATTACHMENT',
  UPLOAD_SUBMISSION_ATTACHMENT: 'UPLOAD_SUBMISSION_ATTACHMENT',
  UPLOAD_SITE_LOGO: 'UPLOAD_SITE_LOGO',
};

export const SYSTEM_MESSAGE_JOB = {
  SEND_BROADCAST: 'SEND_BROADCAST',
};

export const QUESTION_BANK_JOB = {
  IMPORT_QUESTIONS: 'IMPORT_QUESTIONS',
  EXPORT_QUESTIONS: 'EXPORT_QUESTIONS',
};
