export const MAIL_QUEUE = 'MAIL_QUEUE';
export const FILE_UPLOAD_QUEUE = 'FILE_UPLOAD_QUEUE';
export const SYSTEM_MESSAGE_QUEUE = 'SYSTEM_MESSAGE_QUEUE';

export const FILE_UPLOAD_JOB = {
  UPLOAD_ATTACHMENT: 'UPLOAD_ATTACHMENT',
  UPLOAD_CONVERSATION_AVATAR: 'UPLOAD_CONVERSATION_AVATAR',
  UPLOAD_USER_AVATAR: 'UPLOAD_USER_AVATAR',
  UPLOAD_USER_BACKGROUND: 'UPLOAD_USER_BACKGROUND',
};

export const SYSTEM_MESSAGE_JOB = {
  SEND_BROADCAST: 'SEND_BROADCAST',
};
