export enum SocketEvent {
  // User Events
  USER_BLOCKED = 'USER_BLOCKED',
  USER_UNBLOCKED = 'USER_UNBLOCKED',
  USER_DELETED = 'USER_DELETED',
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  PROFILE_STATUS_CHANGE = 'PROFILE_STATUS_CHANGE',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',

  // Message Events
  NEW_MESSAGE = 'NEW_MESSAGE',
  EDIT_MESSAGE = 'EDIT_MESSAGE',
  DELETE_MESSAGE = 'DELETE_MESSAGE',
  MARK_MESSAGE_AS_READ = 'MARK_MESSAGE_AS_READ',
  PIN_MESSAGE = 'PIN_MESSAGE',
  UNPIN_MESSAGE = 'UNPIN_MESSAGE',
  UPDATE_ATTACHMENT = 'UPDATE_ATTACHMENT',

  // FRIEND EVENTS
  SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST',
  FRIEND_REQUEST_STATUS_CHANGE = 'FRIEND_REQUEST_STATUS_CHANGE',
  REMOVE_FRIEND = 'REMOVE_FRIEND',
  BLOCK_FRIEND = 'BLOCK_FRIEND',
  UNBLOCK_FRIEND = 'UNBLOCK_FRIEND',

  // CONVERSATION
  CREATE_CONVERSATION = 'CREATE_CONVERSATION',
  EDIT_CONVERSATION = 'EDIT_CONVERSATION',
  ARCHIVE_CONVERSATION = 'ARCHIVE_CONVERSATION',
  UNARCHIVE_CONVERSATION = 'UNARCHIVE_CONVERSATION',
  MUTE_CONVERSATION = 'MUTE_CONVERSATION',
  UNMUTE_CONVERSATION = 'UNMUTE_CONVERSATION',
  PIN_CONVERSATION = 'PIN_CONVERSATION',
  UNPIN_CONVERSATION = 'UNPIN_CONVERSATION',
  REMOVE_CONVERSATION = 'REMOVE_CONVERSATION',
  BLOCK_CONVERSATION = 'BLOCK_CONVERSATION',
  UNBLOCK_CONVERSATION = 'UNBLOCK_CONVERSATION',
  DELETE_CONVERSATION = 'DELETE_CONVERSATION',
  UPDATE_CONVERSATION_AVATAR = 'UPDATE_CONVERSATION_AVATAR',
  GLOBAL_CONVERSATION_UPDATE = 'GLOBAL_CONVERSATION_UPDATE',

  // Group Events
  ADD_MEMBER_TO_GROUP = 'ADD_MEMBER_TO_GROUP',
  REMOVE_MEMBER_FROM_GROUP = 'REMOVE_MEMBER_FROM_GROUP',
  LEAVE_GROUP = 'LEAVE_GROUP',
  CHANGE_OWNER_OF_GROUP = 'CHANGE_OWNER_OF_GROUP',

  // Join Request Events
  NEW_JOIN_REQUEST = 'NEW_JOIN_REQUEST',
  JOIN_REQUEST_APPROVED = 'JOIN_REQUEST_APPROVED',
  JOIN_REQUEST_REJECTED = 'JOIN_REQUEST_REJECTED',
}

export const getRoomByCode = (code: string) => `room-${code}`;
export const getUserRoomByEmail = (email: string) => `user-room-${email}`;
export const getConversationRoomById = (conversationId: number) =>
  `conversation-room-${conversationId}`;
