export enum SocketEvent {
  USER_BLOCKED = 'USER_BLOCKED',
  USER_UNBLOCKED = 'USER_UNBLOCKED',
  USER_DELETED = 'USER_DELETED',
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  PROFILE_STATUS_CHANGE = 'PROFILE_STATUS_CHANGE',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
  UPDATE_ATTACHMENT = 'UPDATE_ATTACHMENT',
}

export const getUserRoomByEmail = (email: string) => `user-room-${email}`;
